# Generated by Django 5.0.7 on 2024-12-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proffesionalchef',
            name='fe',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='proffesionalchef',
            name='inn',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='proffesionalchef',
            name='ins',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='proffesionalchef',
            name='x',
            field=models.URLField(),
        ),
    ]
